fix(payout-curve): Fix payout_curve crate build
The crate `payout_curve` has a dependency on the internal crate
`trade`. That crate was depending on `bdk`, even though it was
sufficient to depend on `bitcoin`.

By removing the dependency on `bdk` we get rid of the following build
error when running `cargo build -p payout_curve`:

```
error[E0658]: use of unstable library feature 'rustc_private': this
crate is being loaded from the sysroot, an unstable location; did you
mean to load this crate from crates.io via `Cargo.toml` instead?
```